// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Start the audio engine. Call stop_engine first if already running.
void startEngine({
  required String wavPath,
  required bool playOutput,
  required bool writeOutput,
  required String outputPath,
}) => RustLib.instance.api.crateApiEngineApiStartEngine(
  wavPath: wavPath,
  playOutput: playOutput,
  writeOutput: writeOutput,
  outputPath: outputPath,
);

/// Stop the audio engine and release all resources.
void stopEngine() => RustLib.instance.api.crateApiEngineApiStopEngine();

/// Toggle bypass for a slot (0=noise gate … 8=reverb).
void toggleBypass({required int slot, required bool bypass}) => RustLib
    .instance
    .api
    .crateApiEngineApiToggleBypass(slot: slot, bypass: bypass);

/// Set params for a slot via JSON string (see design doc for schema per slot).
void setParam({required int slot, required String json}) =>
    RustLib.instance.api.crateApiEngineApiSetParam(slot: slot, json: json);
